import { Conversation } from "./types";

export const conversations: Conversation[] = [
  {
    id: "self-intro",
    title: "はじめまして",
    titleEn: "Nice to Meet You",
    level: "beginner",
    speaker: "田中さくら",
    speakerDescription: "Your new neighbor who just moved in next door",
    exchanges: [
      {
        speakerMessage:
          "こんにちは！私は田中さくらです。隣に引っ越してきました。よろしくお願いします。",
        speakerMessageTranslation:
          "Hello! I'm Sakura Tanaka. I just moved in next door. Nice to meet you.",
        question: "田中さんは何をしましたか？",
        questionTranslation: "What did Tanaka-san do?",
        choices: [
          "隣から引っ越して出た",
          "隣に引っ越してきた",
          "隣の人に挨拶に来た",
          "隣に住んでいる友達を紹介した",
        ],
        choiceTranslations: [
          "Moved away from next door",
          "Moved in next door",
          "Came to greet the neighbor",
          "Introduced a friend who lives next door",
        ],
        correctChoiceIndex: 1,
        suggestedAnswer:
          "はじめまして！よろしくお願いします。いつ引っ越してきたんですか？",
        suggestedAnswerTranslation:
          "Nice to meet you! Pleased to meet you. When did you move in?",
        answerParts: [
          "はじめまして！",
          "よろしく",
          "お願いします。",
          "いつ",
          "引っ越してきたん",
          "ですか？",
        ],
        vocabulary: [
          { word: "こんにちは", reading: "こんにちは", meaning: "hello" },
          { word: "私", reading: "わたし", meaning: "I, me" },
          { word: "隣", reading: "となり", meaning: "next door, neighbor" },
          { word: "引っ越す", reading: "ひっこす", meaning: "to move (house)" },
          { word: "引っ越し", reading: "ひっこし", meaning: "moving (house)" },
          { word: "よろしくお願いします", reading: "よろしくおねがいします", meaning: "nice to meet you / please take care of me" },
          { word: "はじめまして", reading: "はじめまして", meaning: "nice to meet you (first time)" },
        ],
      },
      {
        speakerMessage:
          "先週の土曜日に引っ越してきました。この辺りは静かでいいですね。",
        speakerMessageTranslation:
          "I moved in last Saturday. This area is nice and quiet, isn't it?",
        question: "田中さんはこの辺りについてどう思っていますか？",
        questionTranslation: "What does Tanaka-san think about this area?",
        choices: [
          "静かすぎてつまらないと思っている",
          "静かだけど住みにくいと思っている",
          "静かでいいと思っている",
          "静かだから引っ越したいと思っている",
        ],
        choiceTranslations: [
          "Thinks it's too quiet and boring",
          "Thinks it's quiet but hard to live in",
          "Thinks it's nice and quiet",
          "Wants to move because it's quiet",
        ],
        correctChoiceIndex: 2,
        suggestedAnswer:
          "そうですね。とても住みやすいですよ。近くにいいスーパーもあります。",
        suggestedAnswerTranslation:
          "That's right. It's very easy to live here. There's a nice supermarket nearby too.",
        answerParts: ["そうですね。", "とても", "住みやすい", "ですよ。", "近くに", "いい", "スーパーも", "あります。"],
        vocabulary: [
          { word: "先週", reading: "せんしゅう", meaning: "last week" },
          { word: "土曜日", reading: "どようび", meaning: "Saturday" },
          { word: "辺り", reading: "あたり", meaning: "area, neighborhood" },
          { word: "静か", reading: "しずか", meaning: "quiet" },
          { word: "住みやすい", reading: "すみやすい", meaning: "easy to live in" },
          { word: "近く", reading: "ちかく", meaning: "nearby" },
          { word: "スーパー", reading: "スーパー", meaning: "supermarket" },
        ],
      },
      {
        speakerMessage:
          "そうですか！スーパーはどこにありますか？まだこの辺りのことがよくわかりません。",
        speakerMessageTranslation:
          "Is that so! Where is the supermarket? I still don't know this area well.",
        question: "田中さんはなぜスーパーの場所を聞いていますか？",
        questionTranslation: "Why is Tanaka-san asking where the supermarket is?",
        choices: [
          "この辺りのことをよく知っているから",
          "スーパーで働きたいから",
          "まだこの辺りのことがよくわからないから",
          "スーパーが遠すぎると聞いたから",
        ],
        choiceTranslations: [
          "Because she knows this area well",
          "Because she wants to work at the supermarket",
          "Because she still doesn't know this area well",
          "Because she heard the supermarket is too far",
        ],
        correctChoiceIndex: 2,
        suggestedAnswer:
          "駅の近くにあります。ここからまっすぐ歩いて五分くらいです。",
        suggestedAnswerTranslation:
          "It's near the station. It's about a 5-minute walk straight from here.",
        answerParts: ["駅の", "近くに", "あります。", "ここから", "まっすぐ", "歩いて", "五分くらい", "です。"],
        vocabulary: [
          { word: "どこ", reading: "どこ", meaning: "where" },
          { word: "まだ", reading: "まだ", meaning: "still, not yet" },
          { word: "わかる", reading: "わかる", meaning: "to understand, to know" },
          { word: "駅", reading: "えき", meaning: "station" },
          { word: "まっすぐ", reading: "まっすぐ", meaning: "straight ahead" },
          { word: "歩く", reading: "あるく", meaning: "to walk" },
          { word: "五分", reading: "ごふん", meaning: "5 minutes" },
        ],
      },
      {
        speakerMessage:
          "ありがとうございます！今度一緒に買い物に行きませんか？",
        speakerMessageTranslation:
          "Thank you! Would you like to go shopping together sometime?",
        question: "田中さんは何と言っていますか？",
        questionTranslation: "What is Tanaka-san saying?",
        choices: [
          "一人で買い物に行きたい",
          "一緒に買い物に行きたくない",
          "今度一緒に買い物に行こうと誘っている",
          "もう買い物に行ってきたと言っている",
        ],
        choiceTranslations: [
          "She wants to go shopping alone",
          "She doesn't want to go shopping together",
          "She's inviting you to go shopping together sometime",
          "She's saying she already went shopping",
        ],
        correctChoiceIndex: 2,
        suggestedAnswer: "いいですね！今週の土曜日はどうですか？",
        suggestedAnswerTranslation: "Sounds good! How about this Saturday?",
        answerParts: ["いいですね！", "今週の", "土曜日は", "どうですか？"],
        vocabulary: [
          { word: "ありがとうございます", reading: "ありがとうございます", meaning: "thank you" },
          { word: "今度", reading: "こんど", meaning: "next time, sometime" },
          { word: "一緒", reading: "いっしょ", meaning: "together" },
          { word: "買い物", reading: "かいもの", meaning: "shopping" },
          { word: "今週", reading: "こんしゅう", meaning: "this week" },
        ],
      },
      {
        speakerMessage: "土曜日はいいですよ！午後二時はどうですか？",
        speakerMessageTranslation: "Saturday works! How about 2 PM?",
        question: "田中さんは土曜日について何と言っていますか？",
        questionTranslation: "What is Tanaka-san saying about Saturday?",
        choices: [
          "土曜日は都合が悪いと言っている",
          "土曜日はいいが、午後二時は無理だと言っている",
          "土曜日はよくて、午後二時を提案している",
          "土曜日の午前中がいいと言っている",
        ],
        choiceTranslations: [
          "She's saying Saturday doesn't work",
          "She's saying Saturday is fine but 2 PM doesn't work",
          "She's saying Saturday is good and suggesting 2 PM",
          "She's saying Saturday morning would be better",
        ],
        correctChoiceIndex: 2,
        suggestedAnswer: "午後二時で大丈夫です。楽しみにしています！",
        suggestedAnswerTranslation: "2 PM works for me. I'm looking forward to it!",
        answerParts: ["午後二時で", "大丈夫です。", "楽しみに", "しています！"],
        vocabulary: [
          { word: "午後", reading: "ごご", meaning: "afternoon, PM" },
          { word: "二時", reading: "にじ", meaning: "2 o'clock" },
          { word: "大丈夫", reading: "だいじょうぶ", meaning: "OK, all right" },
          { word: "楽しみ", reading: "たのしみ", meaning: "looking forward to" },
        ],
      },
    ],
  },
  {
    id: "cafe",
    title: "カフェで",
    titleEn: "At a Cafe",
    level: "beginner",
    speaker: "店員",
    speakerDescription: "A friendly cafe worker",
    exchanges: [
      {
        speakerMessage: "いらっしゃいませ！何名様ですか？",
        speakerMessageTranslation: "Welcome! How many people?",
        question: "店員さんは何を聞いていますか？",
        questionTranslation: "What is the staff asking?",
        choices: [
          "お客さんの名前を聞いている",
          "お客さんが何人か聞いている",
          "お客さんが何を注文するか聞いている",
          "お客さんが予約しているか聞いている",
        ],
        choiceTranslations: [
          "Asking the customer's name",
          "Asking how many people there are",
          "Asking what the customer wants to order",
          "Asking if the customer has a reservation",
        ],
        correctChoiceIndex: 1,
        suggestedAnswer: "一人です。カウンター席はありますか？",
        suggestedAnswerTranslation: "Just one. Do you have counter seats?",
        answerParts: ["一人です。", "カウンター席は", "ありますか？"],
        vocabulary: [
          { word: "いらっしゃいませ", reading: "いらっしゃいませ", meaning: "welcome (to a shop/restaurant)" },
          { word: "何名様", reading: "なんめいさま", meaning: "how many people (polite)" },
          { word: "一人", reading: "ひとり", meaning: "one person" },
          { word: "カウンター席", reading: "カウンターせき", meaning: "counter seat" },
        ],
      },
      {
        speakerMessage:
          "はい、こちらへどうぞ。メニューです。おすすめはアイスコーヒーと抹茶ラテです。",
        speakerMessageTranslation:
          "Yes, please come this way. Here's the menu. Our recommendations are iced coffee and matcha latte.",
        question: "店員さんは何をおすすめしていますか？",
        questionTranslation: "What is the staff recommending?",
        choices: [
          "アイスコーヒーとチーズケーキ",
          "抹茶ラテとチョコレートケーキ",
          "アイスコーヒーと抹茶ラテ",
          "ホットコーヒーと抹茶ラテ",
        ],
        choiceTranslations: [
          "Iced coffee and cheesecake",
          "Matcha latte and chocolate cake",
          "Iced coffee and matcha latte",
          "Hot coffee and matcha latte",
        ],
        correctChoiceIndex: 2,
        suggestedAnswer: "抹茶ラテをお願いします。あと、ケーキはありますか？",
        suggestedAnswerTranslation: "I'll have the matcha latte, please. Also, do you have cake?",
        answerParts: ["抹茶ラテを", "お願いします。", "あと、", "ケーキは", "ありますか？"],
        vocabulary: [
          { word: "こちら", reading: "こちら", meaning: "this way" },
          { word: "どうぞ", reading: "どうぞ", meaning: "please (go ahead)" },
          { word: "おすすめ", reading: "おすすめ", meaning: "recommendation" },
          { word: "抹茶ラテ", reading: "まっちゃラテ", meaning: "matcha latte" },
          { word: "お願いします", reading: "おねがいします", meaning: "please" },
          { word: "あと", reading: "あと", meaning: "also, and" },
          { word: "ケーキ", reading: "ケーキ", meaning: "cake" },
        ],
      },
      {
        speakerMessage:
          "はい、チーズケーキとチョコレートケーキがございます。どちらがよろしいですか？",
        speakerMessageTranslation:
          "Yes, we have cheesecake and chocolate cake. Which would you prefer?",
        question: "店員さんは何を聞いていますか？",
        questionTranslation: "What is the staff asking?",
        choices: [
          "ケーキを食べたいかどうか聞いている",
          "チーズケーキとチョコレートケーキのどちらがいいか聞いている",
          "ケーキのサイズを聞いている",
          "ケーキを持ち帰りたいか聞いている",
        ],
        choiceTranslations: [
          "Asking if you want to eat cake",
          "Asking which you prefer: cheesecake or chocolate cake",
          "Asking what size cake you want",
          "Asking if you want to take the cake to go",
        ],
        correctChoiceIndex: 1,
        suggestedAnswer: "チーズケーキをください。",
        suggestedAnswerTranslation: "I'll have the cheesecake, please.",
        answerParts: ["チーズケーキを", "ください。"],
        vocabulary: [
          { word: "チーズケーキ", reading: "チーズケーキ", meaning: "cheesecake" },
          { word: "チョコレートケーキ", reading: "チョコレートケーキ", meaning: "chocolate cake" },
          { word: "ございます", reading: "ございます", meaning: "to exist (very polite)" },
          { word: "どちら", reading: "どちら", meaning: "which one (polite)" },
          { word: "よろしい", reading: "よろしい", meaning: "good, fine (polite)" },
          { word: "ください", reading: "ください", meaning: "please give me" },
        ],
      },
      {
        speakerMessage:
          "かしこまりました。少々お待ちください。……お待たせしました。抹茶ラテとチーズケーキです。",
        speakerMessageTranslation:
          "Understood. Please wait a moment. ...Sorry for the wait. Here's your matcha latte and cheesecake.",
        question: "「お待たせしました」のあと、店員さんは何をしましたか？",
        questionTranslation: "After saying 'sorry for the wait', what did the staff do?",
        choices: [
          "注文を確認した",
          "注文したものを持ってきた",
          "もう少し待ってほしいと言った",
          "注文を間違えたと言った",
        ],
        choiceTranslations: [
          "Confirmed the order",
          "Brought the ordered items",
          "Asked to wait a little longer",
          "Said they got the order wrong",
        ],
        correctChoiceIndex: 1,
        suggestedAnswer: "ありがとうございます。とても美味しそうですね！",
        suggestedAnswerTranslation: "Thank you. It looks very delicious!",
        answerParts: ["ありがとうございます。", "とても", "美味しそう", "ですね！"],
        vocabulary: [
          { word: "かしこまりました", reading: "かしこまりました", meaning: "understood (very polite)" },
          { word: "少々", reading: "しょうしょう", meaning: "a little, a moment" },
          { word: "お待ちください", reading: "おまちください", meaning: "please wait" },
          { word: "お待たせしました", reading: "おまたせしました", meaning: "sorry for the wait" },
          { word: "美味しそう", reading: "おいしそう", meaning: "looks delicious" },
        ],
      },
      {
        speakerMessage: "ごゆっくりどうぞ。お会計はレジでお願いします。",
        speakerMessageTranslation: "Please take your time. Payment is at the register.",
        question: "店員さんはお会計について何と言っていますか？",
        questionTranslation: "What is the staff saying about paying?",
        choices: [
          "お会計はテーブルでする",
          "お会計はあとで案内する",
          "お会計はレジでする",
          "お会計はカウンターでする",
        ],
        choiceTranslations: [
          "Pay at the table",
          "They'll guide you to pay later",
          "Pay at the register",
          "Pay at the counter",
        ],
        correctChoiceIndex: 2,
        suggestedAnswer: "わかりました。ごちそうさまでした。とても美味しかったです。",
        suggestedAnswerTranslation: "I see. Thank you for the meal. It was very delicious.",
        answerParts: ["わかりました。", "ごちそうさまでした。", "とても", "美味しかったです。"],
        vocabulary: [
          { word: "ごゆっくり", reading: "ごゆっくり", meaning: "please take your time" },
          { word: "お会計", reading: "おかいけい", meaning: "bill, check, payment" },
          { word: "レジ", reading: "レジ", meaning: "register, cash register" },
          { word: "ごちそうさまでした", reading: "ごちそうさまでした", meaning: "thank you for the meal" },
          { word: "美味しい", reading: "おいしい", meaning: "delicious" },
        ],
      },
    ],
  },
  {
    id: "weekend-plans",
    title: "週末の予定",
    titleEn: "Weekend Plans",
    level: "intermediate",
    speaker: "山田けんた",
    speakerDescription: "A friend from work",
    exchanges: [
      {
        speakerMessage: "来週の週末、何か予定ある？映画を見に行かない？",
        speakerMessageTranslation: "Do you have any plans next weekend? Want to go see a movie?",
        question: "山田さんは何と言っていますか？",
        questionTranslation: "What is Yamada-san saying?",
        choices: [
          "来週の予定を聞いて、映画に誘っている",
          "来週の映画の予定をキャンセルしたい",
          "週末に映画を見たが、つまらなかった",
          "来週の週末は予定があるから映画に行けない",
        ],
        choiceTranslations: [
          "Asking about next week's plans and inviting you to a movie",
          "Wants to cancel next week's movie plans",
          "Saw a movie on the weekend but it was boring",
          "Can't go to a movie because he has plans next weekend",
        ],
        correctChoiceIndex: 0,
        suggestedAnswer: "いいね！何の映画を見たい？最近面白いのがあるって聞いたよ。",
        suggestedAnswerTranslation: "Sounds good! What movie do you want to see? I heard there's a good one recently.",
        answerParts: ["いいね！", "何の映画を", "見たい？", "最近", "面白いのが", "あるって", "聞いたよ。"],
        vocabulary: [
          { word: "来週", reading: "らいしゅう", meaning: "next week" },
          { word: "週末", reading: "しゅうまつ", meaning: "weekend" },
          { word: "予定", reading: "よてい", meaning: "plans, schedule" },
          { word: "映画", reading: "えいが", meaning: "movie" },
          { word: "最近", reading: "さいきん", meaning: "recently" },
          { word: "面白い", reading: "おもしろい", meaning: "interesting, fun" },
          { word: "聞く", reading: "きく", meaning: "to hear, to ask" },
        ],
      },
      {
        speakerMessage: "新しいアクション映画が出たんだけど、評判がすごくいいらしいよ。土曜日の午後はどう？",
        speakerMessageTranslation: "A new action movie came out, and I hear it has really good reviews. How about Saturday afternoon?",
        question: "山田さんによると、その映画はどうですか？",
        questionTranslation: "According to Yamada-san, how is the movie?",
        choices: [
          "新しいけど評判はあまりよくないらしい",
          "評判がすごくいいらしい",
          "まだ出ていないけど評判がいいらしい",
          "評判はいいけどアクション映画ではないらしい",
        ],
        choiceTranslations: [
          "It's new but apparently doesn't have great reviews",
          "Apparently it has really good reviews",
          "It's not out yet but apparently has good reviews",
          "It has good reviews but apparently isn't an action movie",
        ],
        correctChoiceIndex: 1,
        suggestedAnswer: "土曜日の午後は大丈夫だよ。何時に待ち合わせする？",
        suggestedAnswerTranslation: "Saturday afternoon works for me. What time should we meet?",
        answerParts: ["土曜日の", "午後は", "大丈夫だよ。", "何時に", "待ち合わせ", "する？"],
        vocabulary: [
          { word: "新しい", reading: "あたらしい", meaning: "new" },
          { word: "アクション", reading: "アクション", meaning: "action" },
          { word: "評判", reading: "ひょうばん", meaning: "reputation, reviews" },
          { word: "すごく", reading: "すごく", meaning: "very, extremely" },
          { word: "らしい", reading: "らしい", meaning: "apparently, it seems" },
          { word: "待ち合わせ", reading: "まちあわせ", meaning: "meeting up, rendezvous" },
        ],
      },
      {
        speakerMessage: "二時の回があるから、一時半に駅前で会わない？映画の前にお昼も食べよう。",
        speakerMessageTranslation: "There's a 2 o'clock showing, so shall we meet at 1:30 in front of the station? Let's eat lunch before the movie too.",
        question: "山田さんの提案はどれですか？",
        questionTranslation: "Which is Yamada-san's suggestion?",
        choices: [
          "二時に駅前で会って、映画の後にお昼を食べる",
          "一時半に駅前で会って、映画の前にお昼を食べる",
          "一時半に映画館で会って、映画の後にお昼を食べる",
          "二時に映画館で会って、映画の前にお昼を食べる",
        ],
        choiceTranslations: [
          "Meet at the station at 2:00, eat lunch after the movie",
          "Meet at the station at 1:30, eat lunch before the movie",
          "Meet at the cinema at 1:30, eat lunch after the movie",
          "Meet at the cinema at 2:00, eat lunch before the movie",
        ],
        correctChoiceIndex: 1,
        suggestedAnswer: "いいよ！駅前のラーメン屋はどう？前に行った時、すごく美味しかったよね。",
        suggestedAnswerTranslation: "Sure! How about the ramen shop in front of the station? It was really good when we went before, right?",
        answerParts: ["いいよ！", "駅前の", "ラーメン屋は", "どう？", "前に行った時、", "すごく", "美味しかった", "よね。"],
        vocabulary: [
          { word: "回", reading: "かい", meaning: "showing, session" },
          { word: "一時半", reading: "いちじはん", meaning: "1:30" },
          { word: "駅前", reading: "えきまえ", meaning: "in front of the station" },
          { word: "会う", reading: "あう", meaning: "to meet" },
          { word: "お昼", reading: "おひる", meaning: "lunch" },
          { word: "食べる", reading: "たべる", meaning: "to eat" },
          { word: "ラーメン屋", reading: "ラーメンや", meaning: "ramen shop" },
          { word: "美味しい", reading: "おいしい", meaning: "delicious" },
        ],
      },
      {
        speakerMessage: "あそこ美味しいよね！じゃあ一時半に駅前のラーメン屋の前で待ち合わせにしよう。",
        speakerMessageTranslation: "That place is good, right! OK, let's meet at 1:30 in front of the ramen shop by the station.",
        question: "待ち合わせはいつ、どこですか？",
        questionTranslation: "When and where is the meeting?",
        choices: [
          "一時半に駅前で",
          "二時にラーメン屋の前で",
          "一時半にラーメン屋の前で",
          "一時半に駅の中で",
        ],
        choiceTranslations: [
          "At 1:30 in front of the station",
          "At 2:00 in front of the ramen shop",
          "At 1:30 in front of the ramen shop",
          "At 1:30 inside the station",
        ],
        correctChoiceIndex: 2,
        suggestedAnswer: "わかった！楽しみだね。じゃあ土曜日にね。",
        suggestedAnswerTranslation: "Got it! I'm excited. See you Saturday then.",
        answerParts: ["わかった！", "楽しみだね。", "じゃあ", "土曜日にね。"],
        vocabulary: [
          { word: "あそこ", reading: "あそこ", meaning: "that place (over there)" },
          { word: "じゃあ", reading: "じゃあ", meaning: "then, well then" },
          { word: "待ち合わせ", reading: "まちあわせ", meaning: "meeting point" },
          { word: "楽しみ", reading: "たのしみ", meaning: "looking forward to" },
          { word: "わかる", reading: "わかる", meaning: "to understand" },
        ],
      },
    ],
  },
];
